# Generated by Django 5.2.4 on 2025-07-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_employee_image_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='desg',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='empid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ename',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(default='Unnamed', max_length=100),
        ),
    ]
